### ISSUE TITLE
undefined for null values

### ISSUE THREAD

**Issue by habib-amara** [kkdrz/blog-examples#1]
https://github.com/kkdrz/blog-examples/blob/6dbd67ce1d40d807ca3e25ca957078efbc76f661/jsonnullable-with-mapstruct/src/main/java/pl/kdrozd/examples/mapper/JsonNullableMapper.java#L16

SUG:
return entity == null ? JsonNullable.undefined() : JsonNullable.of(entity);

**Comment by kkdrz** [comment]
I'm not sure what you mean but assuming that you would like to replace those lines, I'm afraid it won't work.
The purpose of this method is to unpack the `JsonNullable`, extract the wrapped value.

Your code doesn't match the signature of the method:
`default <T> T unwrap(JsonNullable<T> jsonNullable)`
